### ISSUE TITLE
int-conversion warning in lttng-ust-2.13.8

### ISSUE THREAD

**Issue by bd4** [argonne-lcf/THAPI#245]
THAPI will not compile with strict when using lttng-ust-2.13.8 (latest stable as of end of July 2024):
```
/home/bda/hpc/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3.0/lttng-ust-2.13.8-hh7lyjuwernhnezmt57btbqyrb33cuas/include/lttng/ust-tracepoint-event.h:891:39: error: initialization of ‘uint32_t *’ {aka ‘unsigned int *’} from ‘size_t’ {aka ‘long unsigned int’} makes pointer from integer without a cast [-Werror=int-conversion]
  891 |                 _length_type __tmpl = __stackvar.__dynamic_len[__dynamic_len_idx]; \
      |                                       ^~~~~~~~~~
/home/bda/hpc/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3.0/lttng-ust-2.13.8-hh7lyjuwernhnezmt57btbqyrb33cuas/include/lttng/ust-tracepoint-event.h:1031:17: note: in definition of macro ‘LTTNG_UST__TRACEPOINT_EVENT_CLASS’
 1031 |                 _fields                                                       \
      |                 ^~~~~~~
/home/bda/hpc/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3.0/lttng-ust-2.13.8-hh7lyjuwernhnezmt57btbqyrb33cuas/include/lttng/ust-tracepoint-event.h:86:26: note: in expansion of macro ‘LTTNG_UST__TP_PARAMS’
   86 |                          LTTNG_UST__TP_PARAMS(_fields))                 \
      |                          ^~~~~~~~~~~~~~~~~~~~
/home/bda/hpc/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3.0/lttng-ust-2.13.8-hh7lyjuwernhnezmt57btbqyrb33cuas/include/lttng/tracepoint.h:853:41: note: in expansion of macro ‘LTTNG_UST_TRACEPOINT_EVENT’
  853 | #define TRACEPOINT_EVENT                LTTNG_UST_TRACEPOINT_EVENT
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/bda/hpc/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3.0/lttng-ust-2.13.8-hh7lyjuwernhnezmt57btbqyrb33cuas/include/lttng/ust-tracepoint-event.h:23:41: note: in expansion of macro ‘LTTNG_UST_TP_FIELDS’
   23 | #define TP_FIELDS                       LTTNG_UST_TP_FIELDS
      |                                         ^~~~~~~~~~~~~~~~~~~
/home/bda/hpc/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3.0/lttng-ust-2.13.8-hh7lyjuwernhnezmt57btbqyrb33cuas/include/lttng/ust-tracepoint-event-write.h:74:9: note: in expansion of macro ‘lttng_ust__field_sequence_encoded’
   74 |         lttng_ust__field_sequence_encoded(_type, _item, _src, LTTNG_UST_BYTE_ORDER,     \
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/bda/hpc/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3.0/lttng-ust-2.13.8-hh7lyjuwernhnezmt57btbqyrb33cuas/include/lttng/ust-tracepoint-event.h:49:41: note: in expansion of macro ‘lttng_ust_field_sequence_text’
   49 | #define ctf_sequence_text               lttng_ust_field_sequence_text
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
././ze_tracepoints.h:5185:5: note: in expansion of macro ‘ctf_sequence_text’
 5185 |     ctf_sequence_text(uint8_t, pResults_vals, pResults, uint32_t *, ((pCount && pResults ? *pCount : 0)) * sizeof(ze_event_query_kernel_timestamps_results_ext_properties_t))
      |     ^~~~~~~~~~~~~~~~~
      ```
